### PR TITLE
Add the Chiness translation

### PR DESCRIPTION
**Pull request by JiamingLinn**
Add the Chiness translation of the README section

### CODE REVIEW

**Comment by yyx990803** [comment]
Hi - thanks for the PR, we are doing translations via GitLocalize and it's best if you can submit your translations here: https://gitlocalize.com/repo/101/zh/en

**Comment by sotayamashita** [comment]
@JiamingLinn I am an engineer of GitLocalize, If you need any help, please ask me. As a @yyx990803 said, you do not have to use GitLocalize but you will get benefit from it.

**Comment by Jinjiang** [comment]
Oops, @chrisvfritz maybe I've missed the point. Should I make a review here directly without using GitLocalize?

**Comment by chrisvfritz** [comment]
@Jinjiang I don't personally mind where a review. We're not using GitLocalize on the core docs, so I'm not as familiar with the workflow. It looks like this page might also be translated though, so perhaps this PR isn't even necessary?

**Comment by sotayamashita** [comment]
@Jinjiang @chrisvfritz I am an engineer of GitLocalize and I will check it.

**Comment by sotayamashita** [comment]
@JiamingLinn 

> Oops, @chrisvfritz maybe I've missed the point. Should I make a review here directly without using GitLocalize?

You can commit here without using GitLocalize. GitLocalize does not have notification feature so I recommend you use GitHub to comment.

@chrisvfritz
> It looks like this page might already be translated though, so perhaps this PR isn't even necessary?

I think we can close this pull request because the page has already been translated.

**Comment by Jinjiang** [comment]
@sotayamashita Thanks.
@chrisvfritz Yes I think this issue could be (now actually has been) closed.
@dear-lizhihua I find the current version in GitLocalize is different with yours. I suggest to respect that one first. And any suggestion and review is welcome I think. Thanks.

**Comment by dear-lizhihua** [comment]
@jinjiang 
我英语不太好，直接中文说吧。现在是在
 gitlocalize 里面维护文档，然后再通过
 gitlocalize 中提 pr 来合并到当前仓库，是一个单向的维护方式。所以我关闭了这个 pr。
My english is poor, so i directly speak Chinese. It is now
 Gitlocalize inside to maintain the document and then commit pr in GitLocalize, and merge to the current repository, this is a one-way maintenance. So I closed this pr.

**Pull request closed without merging**
