### PR TITLE
[READY TO MERGE] Russian translation

### PR DESCRIPTION
**Pull request by Alex-Sokolov**
README.md not translated. Seems it not used anywhere?

### CODE REVIEW

**Comment by simplesmiler** [comment]
@Alex-Sokolov in english version `README.md` appears to be used as the Introduction page (https://ssr.vuejs.org/en/). Unfortunately I can't not run the gitbook locally to check.

**Comment by Alex-Sokolov** [comment]
@simplesmiler Thanks for notice! Translated README.md

**Comment by simplesmiler** [comment]
@Alex-Sokolov sent review in form of PR, https://github.com/translation-gang/vue-ssr-docs/pull/11
Other than that, translation looks good to me, good job! :+1:

**Comment by Alex-Sokolov** [comment]
@simplesmiler merged your PR :)

**Comment by Alex-Sokolov** [comment]
@kazupon @posva ping :)

**Comment by Alex-Sokolov** [comment]
When it will be available online? :)

**Comment by Alex-Sokolov** [comment]
@kazupon @posva who can publish online?)

**Comment by yyx990803** [comment]
@Alex-Sokolov thanks for the contribution, please be patient and we will deploy when we can.

**Pull request merged**
