### PR TITLE
[Doc FR]: v2.5 update + 1990 french graphie fixes

### PR DESCRIPTION
**Pull request by Haeresis**
Ok for us @postva, just same big typo review for Vue Server Renderer!

### CODE REVIEW

**Comment by Haeresis** [comment]
Hi @posva, @chrisvfritz ! The v2.5 translation are ready.

**Comment by Haeresis** [comment]
I like your new avatar @posva :)

**Comment by posva** [comment]
@Haeresis Hey! Thanks a lot 😄

**Comment by chrisvfritz** [comment]
@Haeresis Ha, I just told him the same thing on our Slack. 😄

**Pull request merged**
